/* Simulation code for odeModel generated by the OpenModelica Compiler OpenModelica 1.26.3. */
#if !defined(odeModel__MODEL_H)
#define odeModel__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "odeModel_functions.h"


extern void odeModel_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void odeModel_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int odeModel_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int odeModel_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int odeModel_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int odeModel_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int odeModel_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int odeModel_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int odeModel_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int odeModel_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int odeModel_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int odeModel_checkForAsserts(DATA *data, threadData_t *threadData);
extern int odeModel_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int odeModel_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int odeModel_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* odeModel_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* odeModel_relationDescription(int i);
extern void odeModel_function_initSample(DATA *data, threadData_t *threadData);
extern int odeModel_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int odeModel_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int odeModel_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int odeModel_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int odeModel_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int odeModel_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int odeModel_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int odeModel_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int odeModel_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int odeModel_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int odeModel_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int odeModel_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int odeModel_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int odeModel_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* odeModel_linear_model_frame(void);
extern const char* odeModel_linear_model_datarecovery_frame(void);
extern int odeModel_mayer(DATA* data, modelica_real** res, short *);
extern int odeModel_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int odeModel_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int odeModel_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int odeModel_setInputData(DATA *data, const modelica_boolean file);
extern int odeModel_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void odeModel_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void odeModel_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int odeModel_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void odeModel_read_simulation_info(SIMULATION_INFO* simulationData);
extern void odeModel_read_input_fmu(MODEL_DATA* modelData);
extern void odeModel_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int odeModel_inputNames(DATA* data, char ** names);
extern int odeModel_dataReconciliationInputNames(DATA* data, char ** names);
extern int odeModel_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int odeModel_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int odeModel_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int odeModel_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "odeModel_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(odeModel__MODEL_H) */


