/* Additional record code for odeModel generated by the OpenModelica Compiler OpenModelica 1.26.3. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "odeModel_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

